name: PublishModule

on:
  push:
    branches: ["main"]

jobs:
  changedFiles:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.changes.outputs.templates }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Changed Modules
        id: changes
        run: |
          set -exo pipefail
          head=$(git rev-parse HEAD)
          current=$(git rev-parse $GITHUB_REF)
          echo "templates=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.event.after }} -- modules/ | grep .bicep$ | xargs)" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: changedFiles
    if: ${{needs.changedFiles.outputs.templates}} && github.event.push
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Login to ACR
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Connect-AzContainerRegistry -Registry ${{ secrets.REGISTRY_NAME }}
          azPSVersion: "latest"

      - name: Publish module and documentation
        shell: pwsh
        run: |
          $templates = ${{needs.changedFiles.outputs.templates}}
          $templates.GetType()

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
