name: PublishModule

on:
  push:
    branches:
      - "main"
      - "refs/pull/**"
  pull_request:
    types: [opened, edited, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Login to ACR
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Connect-AzContainerRegistry -Registry ${{ vars.REGISTRY_NAME }}
          azPSVersion: "latest"

      - name: Publish module and documentation
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if (-not (Test-Path -Path docs)) { mkdir -p docs }
            scripts/Create-BicepDocumentation.ps1 -TemplatePath modules -RegistryName ${{ vars.REGISTRY_NAME }} -Debug *>&1
          azPSVersion: "latest"

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
